In [1]:
import numpy as np
from scipy.optimize import minimize
import pandas as pd

# Q1

In [2]:
def neg_machines(lk):
    l, k = lk
    
    n_machines = 0.05 * (l**(2/3)) * (k**(1/3))
    
    return -1*n_machines

In [3]:
def cons1(lk):
    l,k = lk
    
    return 100000 - 12*l - 15*k

In [4]:
# now we create a dictionary telling the solver what type of constraint and what the function is
constr1 = {'type':'ineq', 'fun': cons1}
# then we put all our constraint dictionaries into a list
constraints = [constr1]

In [5]:
max_machines = minimize(neg_machines,[3,2],constraints=constraints)
print(round(-max_machines.fun))

205


# Q2

In [2]:
df = pd.read_csv('homework4stocks.csv', index_col='Date', parse_dates=True)
df.head()

AA   AAPL    AXP     BA    CAT   CSCO     DD    DIS     EK  \
Date                                                                        
2004-01-01 -0.101  0.055  0.075 -0.009 -0.055  0.061 -0.043  0.029  0.107   
2004-02-01  0.101  0.060  0.031  0.043 -0.030 -0.099  0.035  0.105  0.005   
2004-03-01 -0.074  0.130 -0.028 -0.053  0.044  0.018 -0.064 -0.058 -0.083   
2004-04-01 -0.114 -0.047 -0.056  0.039 -0.012 -0.113  0.017 -0.078 -0.015   
2004-05-01  0.023  0.088  0.036  0.078 -0.031  0.070  0.014  0.019  0.025   

              FDX  ...     KO    MCD    MMM     MO    MRK   MSFT     PG  \
Date               ...                                                    
2004-01-01 -0.003  ... -0.030  0.037 -0.070  0.021  0.030  0.010  0.017   
2004-02-01  0.021  ...  0.015  0.099 -0.009  0.035  0.010 -0.040  0.014   
2004-03-01  0.095  ...  0.012  0.010  0.049 -0.043 -0.074 -0.060  0.023   
2004-04-01 -0.043  ...  0.005 -0.047  0.056  0.017  0.064  0.048  0.014   
2004-05-01  0.023  ...  0.015 -0.030 -0.018 -0.133  0.006  0.004  0.019   

                T    UTX    WMT  
Date                             
2004-01-01 -0.011  0.008  0.015  
2004-02-01 -0.058 -0.032  0.106  
2004-03-01  0.022 -0.063  0.004  
2004-04-01  0.028 -0.001 -0.045  
2004-05-01 -0.048 -0.015 -0.020  

[5 rows x 27 columns]

In [3]:
stock_mean, stock_var =  df.mean(), df.var()

In [8]:
stock_cov = df.cov().values

In [9]:
stock_cov

array([[ 1.36563585e-02,  6.02487030e-03,  7.06265277e-03,
         4.23294395e-03,  8.31847864e-03,  4.40813090e-03,
         5.36510390e-03,  4.89302170e-03,  4.58643028e-03,
         4.91623411e-03,  5.26823599e-03,  1.00601794e-02,
         4.46437474e-03,  3.08413431e-03,  1.01429417e-02,
         1.76411483e-03,  2.92486124e-03,  2.06973633e-03,
         1.88446548e-03,  3.60068421e-03,  1.28289029e-03,
         2.43237697e-03,  3.55242430e-03,  1.58214132e-03,
         2.69640909e-03,  3.63659159e-03,  1.02226726e-03],
       [ 6.02487030e-03,  1.42950752e-02,  6.36688346e-03,
         3.50530827e-03,  4.72908459e-03,  3.31210902e-03,
         3.64106015e-03,  3.47659774e-03,  2.87214662e-03,
         3.34000188e-03,  3.34052444e-03,  8.15288158e-03,
         2.98209023e-03,  2.65774812e-03,  5.08431391e-03,
         1.07330263e-03,  1.64577632e-03,  1.13258835e-03,
         2.76650564e-03,  2.61388158e-03,  2.28809023e-03,
         1.29450564e-03,  3.71042293e-03,  1.25076880e-

In [10]:
weights = np.linspace(0,1, num = 27)


In [11]:
weights @ stock_cov @ weights

0.3491049635865147

In [12]:
def totalVarianceQP(weights):
    return weights.T @ stock_cov @ weights

In [40]:
def totalVariance(weights):
    total_var = 0
    for i in range(len(weights)):
        w_i = weights[i]
        for j in range(len(weights)):
            w_j = weights[j]
            total_var+=w_i*w_j*stock_cov.values[i][j]
    
    
    return total_var

In [13]:
def cons1(weights):
    return sum(weights) - 1

def cons2(weights):
    return weights @ stock_mean - 0.01

# now we create a dictionary telling the solver what type of constraint and what the function is
constr1 = {'type':'eq', 'fun': cons1}
constr2 = {'type':'ineq', 'fun': cons2}
# then we put all our constraint dictionaries into a list
constraints = [constr1, constr2]

In [14]:
weights = np.linspace(0,1, num = 27)
weights = np.ones(27)/27
best_param = minimize(totalVarianceQP, weights, constraints=constraints, bounds=[(0,1)]*27)

In [15]:
best_param.x

array([0.00000000e+00, 5.18341618e-02, 0.00000000e+00, 4.35112845e-04,
       7.25209301e-18, 1.17896476e-17, 0.00000000e+00, 1.17330150e-17,
       3.92444700e-18, 8.95709197e-18, 0.00000000e+00, 0.00000000e+00,
       1.33758652e-03, 1.56125113e-17, 0.00000000e+00, 8.54671166e-02,
       3.01792894e-18, 2.84316578e-02, 1.71317855e-01, 0.00000000e+00,
       2.32483451e-01, 2.90557230e-18, 4.10360599e-18, 9.66903132e-02,
       6.52337205e-02, 0.00000000e+00, 2.66769025e-01])

In [18]:
round(np.sqrt(best_param.fun),2)

0.03

In [21]:
np.sqrt(best_param.fun)

0.029954177792743446

## Sol : 0.08

# Solving as QP

In [22]:
import gurobipy as gp

In [23]:
threshold_return = 0.01
meanvec = stock_mean
Sigma = np.zeros((27,27))
Sigma = stock_cov
w = np.ones(27)/27

print(w @ Sigma @ w)
print(w @ meanvec)



0.002913491079925777
0.007372294372294374


In [24]:
# constraint0: weights sum to 1
# constraint1: mean return is >= 9%

A = np.ones((2,27)) # row 0 is all 1s already

b = np.ones(2)

A[1,:] = meanvec # now change row 1
b[1] = threshold_return # now change row 1

sense = ['=','>'] 



In [25]:
portMod = gp.Model()
portMod_x = portMod.addMVar(27,ub=np.array([1]*27))
portMod_con = portMod.addMConstrs(A, portMod_x, sense, b)
portMod.setMObjective(Sigma,None,0,sense=gp.GRB.MINIMIZE)

portMod.Params.OutputFlag = 0 

portMod.optimize()

Academic license - for non-commercial use only - expires 2022-11-04
Using license file C:\Users\mehen\gurobi.lic


In [26]:
portMod_x.x

array([3.17346016e-10, 5.16918766e-02, 4.15038770e-10, 2.51578013e-07,
       5.97430170e-10, 2.80699686e-09, 6.07062627e-10, 1.58799575e-09,
       2.86695056e-10, 1.17230963e-09, 4.62352150e-10, 2.44411161e-10,
       2.48562725e-02, 4.10925667e-08, 3.54343380e-10, 1.52688079e-02,
       9.83240619e-10, 1.08422640e-05, 1.39411400e-01, 3.35958645e-08,
       2.70171677e-01, 1.21890100e-08, 1.28407380e-09, 1.25559379e-01,
       5.83322023e-02, 1.49415549e-08, 3.14697178e-01])

In [28]:
round(np.sqrt(portMod.objVal),2)

0.03

# Q3

In [25]:
import statsmodels.api as sm

In [36]:
df = pd.read_csv('variable_selection.csv', index_col=0)
df.head()
y = df['y']

for v in [['x1', 'x3'], ['x2', 'x3'], ['x1', 'x2'], ['x3'], ['x2'], ['x1']]:
    print(v)
    X = df[v] 
    X = sm.add_constant(X)
    model = sm.OLS(y,X)
    results = model.fit()
    print(results.ssr)
    print()

['x1', 'x3']
7860.088759733232

['x2', 'x3']
878.181050436763

['x1', 'x2']
26.190873301641904

['x3']
8575.63588048066

['x2']
878.8358232527935

['x1']
7901.2994287817055



## Sol : x1, x2

# Q4

In [141]:
df = pd.read_csv('nflratings.csv', header=None)
df.columns = ['week', 'home_team', 'away_team', 'home_team_score', 'away_team_score']
df.head()
df['score_diff'] = df['home_team_score'] - df['away_team_score']

#### Calculating rating using HW1 method

In [142]:
X = (pd.get_dummies(df['home_team']).astype(int) - pd.get_dummies(df['away_team'])).values

In [143]:
B = df['score_diff'].values

In [144]:
M = np.matmul(X.T, X)
M[len(M) - 1:] = [1]*32
M

array([[16,  0,  0, ...,  0, -1,  0],
       [ 0, 16,  0, ..., -2,  0, -1],
       [ 0,  0, 16, ...,  0,  0,  0],
       ...,
       [ 0, -2,  0, ..., 16,  0, -1],
       [-1,  0,  0, ...,  0, 16,  0],
       [ 1,  1,  1, ...,  1,  1,  1]])

In [145]:
p = np.matmul(X.T, B)

p[len(p) - 1] = 0
p


array([  50,   38,  130,  -68,    7,  -85,   51, -130,  111,    2, -232,
        164,   55,  109,  -90, -130,  -30,  158,  142,  169,  -25,  112,
       -182,   92,   47, -239,  131,   49, -132, -156,  -48,    0],
      dtype=int64)

In [146]:
M_inv = np.linalg.inv(M)
r = np.matmul(M_inv, p)
r

array([ -0.48927724,   4.82728313,   7.77366413,  -1.91359399,
         3.75150804,  -5.29817021,   2.70206238,  -8.08501643,
         7.11381332,   0.64061252, -14.49034857,   7.26186548,
         1.98958419,   5.86039151,  -6.56217794,  -8.10695693,
         1.61185936,   7.0704046 ,  11.12008657,  10.61308031,
         0.08510988,   8.13815522,  -9.96231741,   5.93866274,
         1.78277968, -17.42022332,   7.48340727,   0.24324916,
       -10.16407607,  -5.83089962,  -2.81450237,  -4.87001939])

### Calculating rating using NLP

In [147]:
def generate_df(r):
    ratings = pd.DataFrame({'team':range(1,33), 'rating':r[:-1]})
    
    df1 = df.copy()
    df1 = df1.merge(ratings, left_on='home_team', right_on='team').drop('team', axis = 1).merge(ratings, left_on='away_team', right_on='team', suffixes=('_home', '_away'))
    
    df1['home_adv'] = r[-1]
    
    df1['predited_spread'] = df1['rating_home'] - df1['rating_away'] + df1['home_adv']
    
    df1['predicted_error'] = df1['score_diff'] - df1['predited_spread']
    
    return df1

In [148]:
def prediction_error(r):
    
    df2 = generate_df(r)
    
    return np.sum(df2['predicted_error']**2)

In [158]:
# r = [i for i in range(70, 102)] + [4]
# prediction_error(r)

r = [i for i in range(0, 32)] + [10]
prediction_error(r)

140331

In [159]:
def cons1(r):
    return sum(r[:-1]) - 2720 

# now we create a dictionary telling the solver what type of constraint and what the function is
constr1 = {'type':'eq', 'fun': cons1}
# then we put all our constraint dictionaries into a list
constraints = [constr1]

In [160]:
best_param = minimize(prediction_error,r,constraints=constraints)

In [161]:
best_param.x

array([84.52236238, 89.84145156, 92.74568577, 83.08899343, 88.75996075,
       79.81205281, 87.54405686, 76.88699969, 92.12111254, 85.63576758,
       70.5040612 , 92.25557476, 86.98431487, 90.86233522, 78.43976843,
       76.88821124, 86.61527893, 92.06483946, 96.1226679 , 95.62868612,
       85.09888245, 93.1484246 , 75.03286296, 90.95814551, 86.64231979,
       67.71995301, 92.60578234, 85.24194218, 74.73184122, 79.17109181,
       82.18829211, 80.13628051,  2.1727328 ])

In [162]:
prediction_error(best_param.x)

42925.67976867668

In [163]:
df1 = generate_df(best_param.x)

In [164]:
df1['home_win'] = df1['score_diff'] > 0
df1['predicted_home_win'] = df1['predited_spread'] > 0

In [165]:
TP = sum(df1['home_win'] & df1['predicted_home_win'])
TN = sum((df1['home_win'] == False) & (df1['predicted_home_win']==False))
TP, TN

(109, 72)

In [166]:
Acc = TP+TN
Acc

181

## Sol : 181