In [2]:
import numpy as np

# Q1 (1 pts)


A bank makes four kinds of loans to its customers and these loans yield the following annual interest rates to the bank:
- First mortgage 14%
- Second mortgage 20%
- Home improvement 20%
- Personal overdraft 10%

We are interested in the bank's lending strategy. The information we know is as following:

1. In total $250 million is lent out.
2. First mortgages are 55% of all mortgages (i.e. first and second mortgage) issued.

3. Second mortgages are 25% of all loans issued.
4. The dollar-weighted average interest rate on all loans is 15%.

Calculate the lending strategy using matrix inversion.  How much is lent in **home improvement loans**?

Answer in millions of dollars, rounded to 2 decimal places.  If the answer is $23080444.12, then you should enter 23.08.


In [3]:
a = [
    [1,1,1,1],
    [-9,11,0,0],
    [1,-3,1,1],
    [-1,5,5,-5]
]
b = [250,0,0,0] 

In [4]:
a_inv = np.linalg.inv(a)
x = np.matmul(a_inv, b)
h = round(x[2],2)
h

31.94

# Q2 (1pts)

Rankings are ubiquitous. You may have heard of Google’s PageRank and IMDB movie ratings. The backbone of these systems is Linear Algebra. We want to give you to taste of building your own ranking system to rank sports teams.

In a football league one is interested in modeling the ratings of teams based on the margin of victory and not just the outcomes, win/loss/draw. Consider the following data for five teams playing in such a league

| | Team 1 | Team 2 | Team 3 | Team 4 | Team 5 |
|---:|:---|:---|:---|:---|:---|
| **Team 1** | | 7-52 | 21-24 | 7-38 | 0-45 |
| **Team 2** | 52-7 | | 34-16 | 25-17 | 27-7 |
| **Team 3** | 24-21 | 16-34 | | 7-5 | 3-30 |
| **Team 4** | 38-7 | 17-25 | 5-7 | | 14-52 |
| **Team 5** | 45-0 | 7-27 | 30-3 | 52-14 | |

An entry (i, j) = (x-y) in this table represents a match between team i and team j where team i scored x points and team j scored y points. Our task is to first rate the teams and then convert the ratings to rankings.

Our goal is to find one number (the rating), ri,  for each team, so that when you compare the ratings between 2 teams, the difference in this rating is equal to the difference in points scored when those 2 teams played each other.  For example, team team 4 beat team 1 by a score of 38-7.  The point difference here is 31 points.  So if we compare team 4's rating to team 1's rating, r4 - r1 = 31.  This is not possible however because there are only 5 teams which leads to 5 values of r, and there were 10 games.  This means there are 5 unknowns and 10 equations, which is a system of equations that cannot be solved.  In this problem, our goal is to find the 5 unknowns that get as close as possible to satisfying the 10 equations!  To do this we will first pose the matrix equation with 5 unknowns and 10 equations and then use a trick from regression to find the closest answer possible.

 

We want

yk = ri − rj
Here yk is the difference in points scored by teams i, j in the match k and ri, rj are the ratings for teams i and j respectively. Assume N teams and M games.This won't be possible for every team/game, but the following steps will tell us how to find the best r's.

 

**Part 1**

Pose a matrix equation to solve for individual ratings of the form X r = y, the entries for coefficient matrix X represent the difference in ratings for the opponents in each game and y represents the difference in score of each game. Each row in X is a game between 2 teams.  This is the 5 unknown and 10 equation system.

**Part 2**

Typically the number of games is much greater than the number of teams, which means our system is overdetermined and we cannot solve the matrix equation by simply inverting the coefficient matrix. However, we can solve for approximate rating using least squares. Consider the normal equation for least squares of the form

X⊤X r = X⊤ y

If you don't know how to take matrix transpose in python, you can google it.
Let M = X⊤X. We can interpret the diagonal elements of M as the number of games played by a team and the off diagonal elements of the matrix M as the negation of the number of games played by team i against team j. Similarly the jth entry for the RHS p = X⊤y is the sum of the difference in points for every game played by team j.
Use the information above to determine the entries for M and X⊤y in our new system.

 

**Part 3**

The matrix M is not invertible. So you cannot solve for ratings, r by inverting M. However, to make it invertible you can add a constraint. For simplicity let us assume that all our ratings add to 0.

Modify your matrix equation Mr = p to incorporate this constraint and get a new system  

Mc r = pc.

To do this remove the last row in M and (X⊤ y) and replace it with an equation that guarantees all entries of r sum to 0.

Finally, solve for the ratings of the teams with data above and sort them to get team rankings.

 

Which team is the second best team?

$ Equations for X and y $ 

$$r_{1} - r_{2} = -45$$
$$r_{1} - r_{3} = -3$$
$$r_{1} - r_{4} = -31$$
$$r_{1} - r_{5} = -45$$
$$r_{2} - r_{3} = 18$$
$$r_{2} - r_{4} = 8$$
$$r_{2} - r_{5} = 20$$
$$r_{3} - r_{4} = 2$$
$$r_{3} - r_{5} = -27$$
$$r_{4} - r_{5} = -38$$

In [29]:
X = [
    [1,-1,0,0,0],
    [1,0,-1,0,0],
    [1,0,0,-1,0],
    [1,0,0,0,-1],
    [0,1,-1,0,0],
    [0,1,0,-1,0],
    [0,1,0,0,-1],
    [0,0,1,-1,0],
    [0,0,1,0,-1],
    [0,0,0,1,-1]
]

X = np.array(X)

B = [-45,-3,-31,-45, 18, 8,20, 2, -27, -38]

Need to make $M = X^{T} * X$ and converting last row equal to $[1,1,1,1,1]$

In [37]:
"""
M = [[ 4, -1, -1, -1, -1],
       [-1,  4, -1, -1, -1],
       [-1, -1,  4, -1, -1],
       [-1, -1, -1,  4, -1],
       [-1, -1, -1, -1,  4]]
"""
M = np.matmul(X.T, X)
M[len(M) - 1:] = [1]*5
M

array([[ 4, -1, -1, -1, -1],
       [-1,  4, -1, -1, -1],
       [-1, -1,  4, -1, -1],
       [-1, -1, -1,  4, -1],
       [ 1,  1,  1,  1,  1]])

Need to make $P = X^{T} * B$ and converting last value equal to 0

In [36]:
"""
p = [-124,   91,  -40,  -17,   0]
"""
p = np.matmul(X.T, B)

p[len(p) - 1] = 0
p


array([-124,   91,  -40,  -17,    0])

In [38]:
M_inv = np.linalg.inv(M)
r = np.matmul(M_inv, p)
r

array([-24.8,  18.2,  -8. ,  -3.4,  18. ])

Second Best team : Team E

# Q3 (1pts)



A Lehmer matrix is one whose entries are specified by the following rule

Ai,j = i/j if j > i and Ai,j = j/i otherwise

Write a function named lehmer_entry which takes two arguments and outputs the value of the entry. Then use “for loop(s)” to generate a 20 by 20 Lehmer Matrix.

(Hint: First generate a 4 by 4 matrix with all the elements being 0. Then use for loop(s) and if statement to define the Lehmer matrix. Find the 4 by 4 Lehmer matrix and use the Wikipedia to check. Then you can change the code to run a 20 by 20)

Is A symmetric?


In [6]:
def lehmer_entry(i, j):
    if j>i:
        return i/j
    return j/i

In [7]:
size = 4
m = np.zeros([size, size])
for i in range(size):
    for j in range(size):
        m[i,j] = lehmer_entry(i+1, j+1)
m

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 1.        , 0.66666667, 0.5       ],
       [0.33333333, 0.66666667, 1.        , 0.75      ],
       [0.25      , 0.5       , 0.75      , 1.        ]])

In [8]:
(m == m.T).all()

True

## 20 by 20 Lehmer Matrix. 

In [9]:
size = 20
m = np.zeros([size, size])
for i in range(size):
    for j in range(size):
        m[i,j] = lehmer_entry(i+1, j+1)
m

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
        0.0625    , 0.05882353, 0.05555556, 0.05263158, 0.05      ],
       [0.5       , 1.        , 0.66666667, 0.5       , 0.4       ,
        0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ,
        0.18181818, 0.16666667, 0.15384615, 0.14285714, 0.13333333,
        0.125     , 0.11764706, 0.11111111, 0.10526316, 0.1       ],
       [0.33333333, 0.66666667, 1.        , 0.75      , 0.6       ,
        0.5       , 0.42857143, 0.375     , 0.33333333, 0.3       ,
        0.27272727, 0.25      , 0.23076923, 0.21428571, 0.2       ,
        0.1875    , 0.17647059, 0.16666667, 0.15789474, 0.15      ],
       [0.25      , 0.5       , 0.75      , 1.        , 0.8       ,
        0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ,
        0.36363636, 0.33333333, 0.30769231, 0

In [10]:
(m == m.T).all()

True

# Q4 (1pts)



Going back to the Lehmer matrix problem.

 

Calculate the inverse of A and assign it to C.

Assign [1 2 3 4 5 6 7 8 9 10 10 9 8 7 6 5 4 3 2 1] to d.

Solve for x in the equation Ax = Cd

What is x10 ? Round to 1 decimal place.  Be careful if the answer you get is in scientific notation.


In [11]:
A = m
C = np.linalg.inv(A)
d = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [12]:
Cd = np.matmul(C, d)
x = np.matmul(np.linalg.inv(A), Cd)
x

array([ 3.94535886e-15,  4.73858713e-15, -3.66637660e-14,  6.97867174e-14,
       -8.86980397e-14, -2.89925318e-15,  3.10348242e-13, -5.74832911e-13,
       -2.48120301e+01,  2.00642393e+01,  3.58137507e+01, -3.00626280e+01,
       -3.73699570e-04, -2.77204399e-04, -2.09968769e-04, -1.61954094e-04,
       -1.26922823e-04, -1.00877941e-04,  9.50593309e+01, -1.00062903e+02])

In [13]:
round(x[9],1)

20.1